export const SERVICES = [
  {
    slug: "building-construction",
    name: "Building Construction",
    shortDesc: "End-to-end construction from foundation to handover using ISI-certified materials.",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=80",
    description:
      "We deliver complete building construction services — residential, commercial, and industrial — using ISI-certified cement and steel, advanced RCC techniques, and Vastu-compliant designs. Our team of 80+ engineers and site supervisors ensures every structure is built to last generations.",
    features: [
      { title: "RCC Framework", desc: "Fe500 TMT steel, M25 grade concrete" },
      { title: "Vastu Layout", desc: "Certified expert guidance included" },
      { title: "Waterproofing", desc: "10-year waterproofing warranty" },
      { title: "On-time Delivery", desc: "Penalty clause for delays" },
      { title: "ISI Materials", desc: "Only certified brands used on site" },
      { title: "Structural Engineer", desc: "Licensed engineer assigned per project" },
    ],
  },
  {
    slug: "exterior-design",
    name: "Exterior Design",
    shortDesc: "Stunning façades, landscaping and elevations that make your property stand out.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80",
    description:
      "First impressions last forever. Our exterior design team crafts stunning façades, compound walls, landscaped gardens, and elevation designs that reflect your personality — from classic Karnataka heritage styles to sleek modern aesthetics.",
    features: [
      { title: "3D Visualization", desc: "Preview before construction begins" },
      { title: "Landscaping", desc: "Garden planning and outdoor areas" },
      { title: "Compound & Gate", desc: "Custom compound wall and driveway" },
      { title: "Lighting Design", desc: "Architectural outdoor lighting" },
      { title: "Cladding Options", desc: "Stone, ACP, glass and more" },
      { title: "Colour Consultation", desc: "Professional colour scheme advisory" },
    ],
  },
  {
    slug: "interior-design",
    name: "Interior Design",
    shortDesc: "Premium turnkey interiors — Italian marble, modular kitchens, teak woodwork.",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80",
    description:
      "Our interior design service transforms raw spaces into living masterpieces. From concept boards to final furnishing — we handle everything. Italian marble flooring, custom modular kitchens, designer wardrobes, and smart home integration — all within your budget.",
    features: [
      { title: "Modular Kitchen", desc: "European hinges, soft-close shutters" },
      { title: "False Ceiling", desc: "Gypsum, POP and wooden options" },
      { title: "Premium Flooring", desc: "Marble, vitrified, hardwood choices" },
      { title: "Smart Home", desc: "Automation-ready wiring & panels" },
      { title: "Custom Wardrobes", desc: "Floor-to-ceiling sliding wardrobes" },
      { title: "Lighting Design", desc: "Ambient, task and accent lighting" },
    ],
  },
  {
    slug: "new-home-construction",
    name: "New Home Construction",
    shortDesc: "Custom-designed homes built from ground up — Vastu-compliant, on-time delivery.",
    image: "https://images.unsplash.com/photo-1593696140826-c58b021acf8b?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=1200&q=80",
    description:
      "Build your dream home from scratch with Vaastu Builders. We manage every stage — soil testing, architectural design, MUDA approval, construction, interiors, and handover. Transparent costing, no hidden charges, 100% on-time delivery with a signed agreement.",
    features: [
      { title: "Package Plans", desc: "Silver, Gold and Platinum packages" },
      { title: "MUDA Approval", desc: "We handle all approvals for you" },
      { title: "Soil Testing", desc: "Geo-technical report before construction" },
      { title: "Structural Design", desc: "Licensed structural engineer assigned" },
      { title: "Handover Kit", desc: "Keys + warranty docs + care guide" },
      { title: "Vastu Compliance", desc: "Certified Vastu expert consultation" },
    ],
  },
  {
    slug: "remodeling",
    name: "Remodeling",
    shortDesc: "Transform your existing space with structural upgrades and modern interiors.",
    image: "https://images.unsplash.com/photo-1574359411659-15573a27fd0c?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1574359411659-15573a27fd0c?w=1200&q=80",
    description:
      "Give your existing home or commercial space a fresh lease of life. Whether it's a complete gut renovation, adding a new floor, or a cosmetic makeover — our team executes with minimal disruption, on schedule, and within budget.",
    features: [
      { title: "Floor Addition", desc: "Safe structural load assessment" },
      { title: "Façade Upgrade", desc: "Modern cladding and painting" },
      { title: "Space Planning", desc: "Optimize existing footprint" },
      { title: "Full Interior Redo", desc: "End-to-end interior replacement" },
      { title: "Minimal Disruption", desc: "Phased work to keep you comfortable" },
      { title: "Fixed Price", desc: "No cost escalation once agreed" },
    ],
  },
  {
    slug: "planning",
    name: "Planning & Architecture",
    shortDesc: "MUDA/BDA approvals, architectural drawings, structural designs and project planning.",
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1200&q=80",
    description:
      "Our licensed architects and structural engineers provide comprehensive planning services — from initial concept sketches to detailed working drawings, MUDA/BDA plan sanction, and structural certification.",
    features: [
      { title: "Architectural Drawing", desc: "2D & 3D plans, elevations, sections" },
      { title: "Approval Liaison", desc: "MUDA, BDA, RERA submissions" },
      { title: "Structural Design", desc: "IS code compliant structural drawings" },
      { title: "3D Rendering", desc: "Photorealistic previews before build" },
      { title: "Site Analysis", desc: "Soil, sun, wind and Vastu study" },
      { title: "Cost Estimation", desc: "Detailed BOQ and rate analysis" },
    ],
  },
];

export const PROJECTS = [
  {
    id: 1,
    name: "Vaastu Royal Towers",
    type: "Residential",
    location: "Vijayanagar, Mysore",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=700&q=80",
    units: "72 Units",
    config: "3 & 4 BHK",
    area: "1,450–2,200 sqft",
    floors: "G + 9",
    price: "₹68L – ₹1.2Cr",
    year: "2023",
  },
  {
    id: 2,
    name: "Vaastu Business Park",
    type: "Commercial",
    location: "Hebbal Ring Road, Mysore",
    status: "Ongoing",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=700&q=80",
    units: "1.2L sqft",
    config: "Office & Retail",
    area: "500–5,000 sqft",
    floors: "G + 6",
    price: "₹80L – ₹4Cr",
    year: "2026",
  },
  {
    id: 3,
    name: "Vaastu Serenity Villas",
    type: "Luxury Villas",
    location: "Kuvempunagar, Mysore",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=700&q=80",
    units: "24 Villas",
    config: "4 BHK",
    area: "3,200 sqft",
    floors: "G + 2",
    price: "₹1.5Cr – ₹2.2Cr",
    year: "2022",
  },
  {
    id: 4,
    name: "Vaastu Green Meadows",
    type: "Residential",
    location: "Nanjangud Road, Mysore",
    status: "Ongoing",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=700&q=80",
    units: "120 Units",
    config: "2 & 3 BHK",
    area: "900–1,450 sqft",
    floors: "G + 7",
    price: "₹42L – ₹75L",
    year: "2025",
  },
  {
    id: 5,
    name: "Vaastu Tech Square",
    type: "IT Park",
    location: "Saraswathipuram, Mysore",
    status: "Completed",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=700&q=80",
    units: "80,000 sqft",
    config: "IT / Office",
    area: "1,000–10,000 sqft",
    floors: "G + 5",
    price: "Fully Leased",
    year: "2021",
  },
  {
    id: 6,
    name: "Vaastu Horizon Township",
    type: "Township",
    location: "Mysore–Bangalore Highway",
    status: "Ongoing",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=700&q=80",
    units: "350 Plots + Villas",
    config: "Plots & 3BHK Villas",
    area: "1,200–4,000 sqft",
    floors: "G + 2 (Villas)",
    price: "₹28L – ₹1.8Cr",
    year: "2026",
  },
];

export const PACKAGES = [
  {
    tag: "Silver Package",
    name: "Essential Home",
    price: "₹1,599 / sqft",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
    included: [
      "Cement: Ultratech / ACC (53 grade)",
      "Steel: Fe500 TMT bars",
      "Brick wall (9-inch solid)",
      "Vitrified tile flooring (₹45/sqft)",
      "Basic bathroom fittings (Cera)",
      "2-coat exterior emulsion paint",
      "Electrical: Finolex wiring",
      "Overhead tank – 1000L capacity",
    ],
    excluded: [
      "Modular kitchen",
      "False ceiling work",
      "Premium / imported tiles",
      "Landscaping & compound",
      "Home automation",
      "Generator / DG backup",
      "Premium CP fittings",
      "Built-in wardrobes",
    ],
  },
  {
    tag: "Gold Package",
    name: "Premium Home",
    price: "₹1,999 / sqft",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
    included: [
      "Everything in Silver Package +",
      "Kajaria / RAK ceramic tiles",
      "Modular kitchen (basic – Sleek)",
      "False ceiling in 2 rooms (gypsum)",
      "CP fittings – Parryware / Jaquar",
      "Premium exterior texture paint",
      "Video door phone",
      "Power backup wiring points",
    ],
    excluded: [
      "Home automation system",
      "Full landscaping",
      "Premium CP fittings (Grohe)",
      "3D elevation design",
      "Elevator provision",
      "Solar rooftop system",
      "Imported marble flooring",
      "Jacuzzi / bathtub",
    ],
  },
  {
    tag: "Platinum Package",
    name: "Luxury Home",
    price: "₹2,599 / sqft",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80",
    included: [
      "Everything in Gold Package +",
      "Full modular kitchen (Häfele)",
      "False ceiling all rooms (POP/wood)",
      "Kohler / Grohe CP fittings",
      "3D elevation design included",
      "Landscaping & driveway",
      "Home automation-ready wiring",
      "Generator & solar power points",
    ],
    excluded: [
      "Elevator (optional add-on)",
      "Imported marble (on request)",
      "Swimming pool",
      "Smart home system devices",
      "Imported kitchen appliances",
      "Custom wall murals / art",
    ],
  },
  {
    tag: "Commercial Package",
    name: "Commercial Build",
    price: "₹2,200 / sqft",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
    included: [
      "RCC framed structure (M30 grade)",
      "Fire NOC compliance layout",
      "BESCOM LT/HT connection points",
      "Passenger lift shaft provision",
      "Common area vitrified flooring",
      "Commercial-grade wiring (3-phase)",
      "Stilt + 2-level parking area",
      "CCTV & security access points",
    ],
    excluded: [
      "Office / retail interiors",
      "Furniture & fixtures",
      "IT / server infrastructure",
      "Branding & signage",
      "DG generator set",
      "Server / data room setup",
    ],
  },
];

export const REVIEWS = [
  {
    initials: "RG",
    name: "Rajesh Gowda",
    project: "Vaastu Royal Towers, Vijayanagar",
    rating: 5,
    text: "Vaastu Builders delivered our 3BHK apartment 6 weeks ahead of schedule. The quality of RCC work, the marble flooring, and the modular kitchen are beyond what we expected at this price. Truly Mysore's best!",
  },
  {
    initials: "PN",
    name: "Priya Nagarajan",
    project: "Vaastu Serenity Villas, Kuvempunagar",
    rating: 5,
    text: "As an NRI investing from the US, I was worried about transparency. But Vaastu's team gave weekly photo updates, handled all RERA paperwork, and the villa exceeded expectations. Will invest again!",
  },
  {
    initials: "SK",
    name: "Suresh Kumar",
    project: "Vaastu Tech Square, Saraswathipuram",
    rating: 5,
    text: "We hired Vaastu for our office interior and they transformed a bare shell into a stunning 3,000 sqft workspace. The lighting design and wooden paneling are getting compliments from every client.",
  },
  {
    initials: "MI",
    name: "Meena Iyengar",
    project: "Home Renovation, Jayalakshmipuram",
    rating: 4,
    text: "The renovation of our 20-year-old house was handled professionally. They added a floor, redid the interiors and upgraded the façade. Our neighbours thought we built a new house. Outstanding!",
  },
  {
    initials: "VR",
    name: "Venkatesh Rao",
    project: "New Home, Hebbal, Mysore",
    rating: 5,
    text: "From planning to possession in 18 months — remarkable! The Vastu consultant, architect, and site engineer worked together seamlessly. The interior package gave our home a premium hotel-like feel.",
  },
  {
    initials: "AB",
    name: "Anjali Bhat",
    project: "MUDA Approval & Construction, Mysore",
    rating: 5,
    text: "Vaastu's planning team handled our MUDA approval in 45 days when others quoted 6 months. Strong knowledge of Mysore's building regulations and very professional to work with.",
  },
];

export const GALLERY_IMAGES = [
  { src: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80", label: "Luxury Villa Exterior" },
  { src: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&q=80", label: "Modern Modular Kitchen" },
  { src: "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=500&q=80", label: "Premium Living Room" },
  { src: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=500&q=80", label: "Construction Progress" },
  { src: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=500&q=80", label: "Master Bedroom Suite" },
  { src: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=500&q=80", label: "Commercial Complex" },
  { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&q=80", label: "Modern Façade Design" },
];
